version: "2"
services:
  signaling:
    build:
      context: ..
      dockerfile: docker/Dockerfile.signaling
    restart: on-failure
    privileged: true
    volumes:
      - ../frame:/container/app
      # separate the host machine node_modules from the docker image
      - /container/app/node_modules
    ports:
      - 8080:8080
      - 8443:8443
    entrypoint: ["/bin/bash", "-c", "npm run dev:msteams"]

  ingress:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ingress
    depends_on:
      - signaling
    restart: on-failure
    privileged: true
    ports:
      - 10000-10005:10000-10005/udp
    entrypoint: [
        "/bin/bash",
        "-c",
        "./frame-mediasoup \
        -a 127.0.0.1 \
        -i true \
        -e false \
        -u signaling:1188 \
        -w 4 \
        -t false \
        -r us-west-2 \
        -p 10000",
      ]

  egress:
    build:
      context: ..
      dockerfile: docker/Dockerfile.egress
    depends_on:
      - signaling
    restart: on-failure
    privileged: true
    ports:
      - 20000-20005:20000-20005/udp
    entrypoint: [
        "/bin/bash",
        "-c",
        "./frame-mediasoup \
        -a 127.0.0.1 \
        -i false \
        -e true \
        -u signaling:1188 \
        -w 4 \
        -t false \
        -r us-west-2 \
        -p 20000",
      ]
