name: Audit Check

on:
  pull_request:
    branches:
      - production
      - staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tsc:
    name: NPM Audit check
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node.js dependencies (frame folder)
        run: npm ci
        working-directory: ./frame

      - name: Run audit check (frame folder)
        run: npm audit
        working-directory: ./frame

      - name: Install Node.js dependencies (serverless folder)
        run: npm ci
        working-directory: ./serverless/functions

      - name: Run audit check (serverless folder)
        run: npm audit
        working-directory: ./serverless/functions
