name: Bottest Build and Deploy - Docker

on:
  push:
    branches: [production]
    tags: [bottest]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build docker image that runs test bot
        run: |
          docker build \
                 --file docker/Dockerfile.bottest \
                 --tag bottest:latest .

      - name: Publish docker bottest image to AWS Elastic Container Registry
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.DEV_AWS_KEY_ID }}
          secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: bottest:latest
