name: Build Check

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tsc:
    name: npm build check
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies (frame folder)
        run: npm ci
        working-directory: ./frame

      - name: Run build check script (frame folder)
        run: npm run build -- --skipSourcemaps
        working-directory: ./frame
