name: Tag/Nightly Development Deployment for Frame

on:
  workflow_dispatch: # Allows manual triggering
  push:
    tags:
      - alpha
      - beta
      - whitelabel
  schedule:
    - cron: "0 6 * * *" # Runs every day at 6:00 AM UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  webapp:
    uses: ./.github/workflows/module-webapp-aws.yml
    needs: dockers
    with:
      S3BaseName: ${GITHUB_REF_NAME##*/}.framevr.io
      MainlineBuildCommand: "build:dev:sourcemaps"
      QuickBuildCommand: "build:dev:quick"
      enableMainline: true
      enableMainlineSourcemaps: false
      enableQuick: true
      ImmersServer: "https://i.${GITHUB_REF_NAME##*/}.framevr.io"
      BrandingName: "${GITHUB_REF_NAME##*/}"
      HomeRedirect: '"https://docs.framevr.io"'
      OutLink: "https://${GITHUB_REF_NAME##*/}.framevr.io"
      MetaImage: "https://${GITHUB_REF_NAME##*/}.framevr.io/assets/meta-image.png"
    secrets:
      AWS_KEY_ID: ${{ secrets.DEV_AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      MainlineCloudfrontDistribution: ${{ secrets.DEV_MAINLINE_CLOUDFRONT }}
      QuickCloudfrontDistribution: ${{ secrets.DEV_QUICK_CLOUDFRONT }}

  dockers:
    uses: ./.github/workflows/module-dockers-aws.yml
    with:
      AWSRegion: us-east-1
    secrets:
      AWS_KEY_ID: ${{ secrets.DEV_AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

  awsecs-common:
    uses: ./.github/workflows/module-ecs-common-aws.yml
    needs: dockers
    with:
      AWSECR: 277920618471
      AWSRegion: us-east-1
    secrets:
      AWS_KEY_ID: ${{ secrets.DEV_AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

  awsecs-regional:
    uses: ./.github/workflows/module-ecs-regional-aws.yml
    needs: dockers
    with:
      AWSECR: 277920618471
      AWSRegion: "['us-east-1']"
    secrets:
      AWS_KEY_ID: ${{ secrets.DEV_AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

  healthcheck:
    runs-on: ubuntu-latest
    needs: 
      - webapp
      - awsecs-regional
      - awsecs-common
    steps:
      - name: Set env variable for ref tag
        run: |
          echo "DEPLOYMENT_NAME=$(echo ${GITHUB_REF_NAME##*/})" >> $GITHUB_ENV
      - name: Webapp Health Check
        uses: jtalk/url-health-check-action@v2
        with:
          url: "https://${{ env.DEPLOYMENT_NAME }}.framevr.io"
          follow-redirect: true
          max-attempts: 15
          retry-delay: 15s
      - name: API Health Check
        uses: jtalk/url-health-check-action@v2
        with:
          url: "https://api.${{ env.DEPLOYMENT_NAME }}.framevr.io/uptime"
          follow-redirect: true
          max-attempts: 15
          retry-delay: 15s
      - name: Immers server Health Check
        uses: jtalk/url-health-check-action@v2
        with:
          url: "https://i.${{ env.DEPLOYMENT_NAME }}.framevr.io/auth/login"
          max-attempts: 15
          retry-delay: 15s
          retry-all: true
