name: Diagnostics Debugging Interface for Frame

on:
  push:
    tags:
      - diagnostics
    branches:
      - production


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  webapp:
    uses: ./.github/workflows/module-webapp-aws.yml
    with:
      S3BaseName: diagnostics.framevr.io
      MainlineBuildCommand: "build:diag"
      QuickBuildCommand: "build:dev:quick"
      enableMainline: true
      enableMainlineSourcemaps: true
      enableQuick: false
      ImmersServer: "i.diagnostics.framevr.io"
      BrandingName: "diagnostics"
      HomeRedirect: '"https://docs.framevr.io"'
      OutLink: "https://diagnostics.framevr.io"
      MetaImage: "https://diagnostics.framevr.io/assets/meta-image.png"
    secrets:
      AWS_KEY_ID: ${{ secrets.DEV_AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      MainlineCloudfrontDistribution: ${{ secrets.DIAGNOSTICS_CLOUDFRONT }}
      QuickCloudfrontDistribution: ""

  healthcheck:
    runs-on: ubuntu-latest
    needs: 
      - webapp
    steps:
      - name: Webapp Health Check
        uses: jtalk/url-health-check-action@v2
        with:
          url: "https://diagnostics.framevr.io"
          follow-redirect: true
          max-attempts: 15
          retry-delay: 15s
