name: Production Deployment for Quick Interface Only

on:
  push:
    tags:
      - quick/production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  webapp:
    uses: ./.github/workflows/module-webapp-aws.yml
    with:
      S3BaseName: ${GITHUB_REF_NAME##*/}.framevr.io
      MainlineBuildCommand: "build"
      QuickBuildCommand: "build:quick"
      enableMainline: false
      enableQuick: true
      ImmersServer: "https://i.framevr.io"
      BrandingName: "Frame"
      OutLink: "https://framevr.io"
      MetaImage: "https://framevr.io/assets/meta-image.png"
      FirebaseAPIKey: ${{ secrets.PRODUCTION_FIREBASE_API_KEY }}
      FirebaseProjectID: ${{ secrets.PRODUCTION_FIREBASE_PROJECT_ID }}
      FirebaseMessagingSenderId: ${{ secrets.PRODUCTION_FIREBASE_MESSAGING_SENDER_ID }}
      FirebaseAppId: ${{ secrets.PRODUCTION_FIREBASE_APP_ID }}
      GoogleClientId: ${{ secrets.PRODUCTION_GOOGLE_CLIENT_ID }}
      CloudinaryUploadPreset: ${{ secrets.PRODUCTION_CLOUDINARY_UPLOAD_PRESET }}
      Plausible: ${{ secrets.PRODUCTION_PLAUSIBLE }}
      QuickHelpMainId: ${{ secrets.PRODUCTION_QUICKHELP_MAIN_ID }}
      QuickHelpGroupId: ${{ secrets.PRODUCTION_QUICKHELP_GROUP_ID }}
    secrets:
      AWS_KEY_ID: ${{ secrets.PRODUCTION_AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
      MainlineCloudfrontDistribution: ${{ secrets.PRODUCTION_MAINLINE_CLOUDFRONT }}
      QuickCloudfrontDistribution: ${{ secrets.PRODUCTION_QUICK_CLOUDFRONT }}

  healthcheck:
    runs-on: ubuntu-latest
    needs:
      - webapp

    steps:
      - name: Quick Interface Webapp Health Check
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://quick.framevr.io
          follow-redirect: true
          max-attempts: 15
          retry-delay: 15s
      - name: API Health Check
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://api.quick.framevr.io/uptime
          follow-redirect: true
          max-attempts: 15
          retry-delay: 15s
      - name: Immers server Health Check
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://i.framevr.io/auth/login
          max-attempts: 15
          retry-delay: 15s
          retry-all: true
