name: Unit Tests

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  severless:
    name: serverless unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./serverless/functions

      - name: Run tests
        run: npm run test
        working-directory: ./serverless/functions

#  webapp-visual-regression:
#    name: Mainline interface visual regression tests
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Check out Git repository
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 2
#      - name: Build in development mode using docker
#        run: docker-compose --file docker/docker-compose.yml up --detach
#      - name: Build in development mode using docker
#         run: docker-compose --file docker/docker-compose.unittest.yml up
